### ISSUE TITLE
Not working on Deno v0.23.0

### ISSUE THREAD

**Issue by suguru03** [keroxp/deno-redis#25]
I'm having this issue with Deno v0.23.0. Do you have any suggestions or any chance to fix it? 
Now, I'm using v0.22.0 because of the issue.

```ts
► https://deno.land/std@v0.20.0/io/bufio.ts:218:37

218     return new TextDecoder().decode(buffer || undefined);
                                        ~~~~~~~~~~~~~~~~~~~

error TS2322: Type 'number | unique symbol' is not assignable to type 'number'.
  Type 'unique symbol' is not assignable to type 'number'.

► https://raw.githubusercontent.com/keroxp/deno-redis/master/io.ts:82:5

82     buf[loc++] = d;
       ~~~~~~~~~~
```
